server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://47.105.77.138:3306/mars?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 47.105.77.138
    port: 6379
    password:
  application:
    name: order

redisson:
  address: redis://${spring.redis.host}:${spring.redis.port}
  password: ${spring.redis.password}