server:
  port: 8081

system:
  shiro:
    login: /login
    logout: /logout

#spring:
#  datasource:
#    url: jdbc:mysql://47.105.77.138:3306/libary?useUnicode=true&characterEncoding=UTF-8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: password
#    type: com.alibaba.druid.pool.DruidDataSource

